In [29]:
# Load Iris Dataset
import numpy as np
from sklearn import datasets

# Load Dataset with first 2 Features
iris = datasets.load_iris()
x = iris.data[:, :2]
y = iris.target
print(x.shape)
print(y.shape)

# Dataset variables
num_samples = x.shape[0]
num_features = x.shape[1]
num_classes = 3
test_size = 20
train_size = num_samples - test_size

# Split Data in Train and Testset
indices = np.random.permutation(num_samples)
x_train = x[indices[:-20]]
y_train = y[indices[:-20]]

x_test = x[indices[-20:]]
y_test = y[indices[-20:]]

(150, 2)
(150,)


In [30]:
# Training Size
print(x_train.shape)
print(y_train.shape)

# Testing Size
print(x_test.shape)
print(y_test.shape)

(130, 2)
(130,)
(20, 2)
(20,)


In [31]:
# Model
from sklearn.neighbors import KNeighborsClassifier

neighbors = [i for i in range(1, 11)] # [1, 2, ...., 10]
weights = ["uniform", "distance"]

# 10 x 2 = 20 Modelle
for neighbor in neighbors:
    for weight in weights:
        knn = KNeighborsClassifier(n_neighbors=neighbor, weights=weight)
        knn.fit(x_train, y_train)
        score = knn.score(x_test, y_test)
        print("Score for setup: ", neighbor, " N, ", weight, " W - Score = ", score) # Score: Genauigkeit (Accuracy)

Score for setup:  1  N,  uniform  W - Score =  0.55
Score for setup:  1  N,  distance  W - Score =  0.55
Score for setup:  2  N,  uniform  W - Score =  0.6
Score for setup:  2  N,  distance  W - Score =  0.55
Score for setup:  3  N,  uniform  W - Score =  0.65
Score for setup:  3  N,  distance  W - Score =  0.6
Score for setup:  4  N,  uniform  W - Score =  0.55
Score for setup:  4  N,  distance  W - Score =  0.6
Score for setup:  5  N,  uniform  W - Score =  0.65
Score for setup:  5  N,  distance  W - Score =  0.6
Score for setup:  6  N,  uniform  W - Score =  0.7
Score for setup:  6  N,  distance  W - Score =  0.6
Score for setup:  7  N,  uniform  W - Score =  0.75
Score for setup:  7  N,  distance  W - Score =  0.6
Score for setup:  8  N,  uniform  W - Score =  0.65
Score for setup:  8  N,  distance  W - Score =  0.6
Score for setup:  9  N,  uniform  W - Score =  0.8
Score for setup:  9  N,  distance  W - Score =  0.6
Score for setup:  10  N,  uniform  W - Score =  0.65
Score for se

In [35]:
# Use "best Setup"
best_neighbor = 4
best_weight = "distance"

knn = KNeighborsClassifier(n_neighbors=best_neighbor, weights=best_weight)
knn.fit(x_train, y_train)

pred = knn.predict(x_test)
pred_prob = knn.predict_proba(x_test)

print("Predictions vs. Classes:")
print("Pred: ", pred)
print("Class: ", y_test)
print("\nPrediction Probs:")
print(pred_prob)

Predictions vs. Classes:
Pred:  [1 1 1 2 2 2 1 2 2 2 0 2 2 0 0 1 0 2 0 1]
Class:  [1 2 2 1 2 2 2 1 2 2 0 1 1 0 0 1 0 2 0 2]

Prediction Probs:
[[0.         1.         0.        ]
 [0.         0.58578644 0.41421356]
 [0.         0.5        0.5       ]
 [0.         0.         1.        ]
 [0.         0.         1.        ]
 [0.         0.19074357 0.80925643]
 [0.         1.         0.        ]
 [0.         0.33333333 0.66666667]
 [0.         0.         1.        ]
 [0.         0.         1.        ]
 [1.         0.         0.        ]
 [0.         0.24264069 0.75735931]
 [0.         0.         1.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         0.58278678 0.41721322]
 [1.         0.         0.        ]
 [0.         0.         1.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]]
