In [120]:
import numpy as np
np.random.seed(42)
from sklearn import datasets

### Dataset preparation

In [121]:
iris = datasets.load_iris()

x = iris.data[:, :2] # [:, [0, 1]]
y = iris.target

class_names = iris.target_names
discription = iris.DESCR

In [122]:
# print(f"class_names:\n{class_names}")
# print(f"discription:\n{discription}")

In [123]:
print(f"x shape:\n{x.shape}")
print(f"y shape:\n{y.shape}")

print(f"x:\n{x}")
print(f"y:\n{y}")

x shape:
(150, 2)
y shape:
(150,)
x:
[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.6]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  3.3]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 

### Dataset Split

In [124]:
num_samples = x.shape[0]
num_features = x.shape[1]
num_classes = y.shape[0]

print(f"num_samples: {num_samples}")
print(f"num_features: {num_features}")
print(f"num_classes: {num_classes}")

num_samples: 150
num_features: 2
num_classes: 150


In [125]:
test_size = num_samples // 3
random_idxs = np.random.permutation(num_samples)

x_train = x[random_idxs[:-test_size]]
y_train = y[random_idxs[:-test_size]]

x_test = x[random_idxs[-test_size:]]
y_test = y[random_idxs[-test_size:]]

In [126]:
print(f"x_train shape:\n{x_train.shape}")
print(f"y_train shape:\n{y_train.shape}")

print(f"x_test shape:\n{x_test.shape}")
print(f"y_test shape:\n{y_test.shape}")

x_train shape:
(100, 2)
y_train shape:
(100,)
x_test shape:
(50, 2)
y_test shape:
(50,)


### KNN Model

In [127]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train, y_train)

accuracy = clf.score(x_test, y_test)
print(f"accuracy: {accuracy*100.0:.4}%")

y_pred = clf.predict(x_test)
print(f"y_pred:\n{y_pred}")

accuracy: 58.0%
y_pred:
[0 0 0 2 1 0 1 1 0 1 2 1 2 2 0 2 2 2 2 1 2 1 2 1 0 1 2 1 0 1 1 2 0 1 0 2 2
 2 1 2 2 2 1 2 0 1 1 0 2 2]


### Try different hyperparameters

In [128]:
n_neighbors = [n_neighbor for n_neighbor in range(1, 11)] # [1, 2, ..., 10]
weight_modes = ['uniform', 'distance']

# 10 x 2 = 20 Models
for n_neighbor in n_neighbors:
    for weight_mode in weight_modes:
        clf = KNeighborsClassifier(
            n_neighbors=n_neighbor,
            weights=weight_mode
        )
        clf.fit(x_train, y_train)
        accuracy = clf.score(x_test, y_test)
        print(f"Neighbors: {n_neighbor}  Weight: {weight_mode}  Score: {accuracy:.4}")

Neighbors: 1  Weight: uniform  Score: 0.68
Neighbors: 1  Weight: distance  Score: 0.68
Neighbors: 2  Weight: uniform  Score: 0.54
Neighbors: 2  Weight: distance  Score: 0.68
Neighbors: 3  Weight: uniform  Score: 0.58
Neighbors: 3  Weight: distance  Score: 0.56
Neighbors: 4  Weight: uniform  Score: 0.64
Neighbors: 4  Weight: distance  Score: 0.66
Neighbors: 5  Weight: uniform  Score: 0.68
Neighbors: 5  Weight: distance  Score: 0.62
Neighbors: 6  Weight: uniform  Score: 0.68
Neighbors: 6  Weight: distance  Score: 0.62
Neighbors: 7  Weight: uniform  Score: 0.72
Neighbors: 7  Weight: distance  Score: 0.66
Neighbors: 8  Weight: uniform  Score: 0.74
Neighbors: 8  Weight: distance  Score: 0.68
Neighbors: 9  Weight: uniform  Score: 0.74
Neighbors: 9  Weight: distance  Score: 0.72
Neighbors: 10  Weight: uniform  Score: 0.66
Neighbors: 10  Weight: distance  Score: 0.72


### Best KNN Model

In [129]:
clf = KNeighborsClassifier(
    n_neighbors=8,
    weights="uniform"
)
clf.fit(x_train, y_train)

accuracy = clf.score(x_test, y_test)
print(f"accuracy: {accuracy*100.0:.4}%")

y_pred = clf.predict(x_test)
print(f"y_pred:\n{y_pred}")

y_pred_proba = clf.predict_proba(x_test)
print(f"y_pred_proba:\n{y_pred_proba}")

accuracy: 74.0%
y_pred:
[0 0 0 2 1 0 1 2 0 1 2 2 2 1 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 1 0 2 2
 2 1 2 2 2 1 1 0 1 0 0 1 2]
y_pred_proba:
[[1.    0.    0.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.125 0.875]
 [0.    0.5   0.5  ]
 [1.    0.    0.   ]
 [0.    0.625 0.375]
 [0.    0.375 0.625]
 [1.    0.    0.   ]
 [0.    0.5   0.5  ]
 [0.    0.125 0.875]
 [0.    0.375 0.625]
 [0.    0.375 0.625]
 [0.    0.5   0.5  ]
 [1.    0.    0.   ]
 [0.    0.375 0.625]
 [0.    0.625 0.375]
 [0.    0.375 0.625]
 [0.    0.625 0.375]
 [0.125 0.875 0.   ]
 [0.    0.625 0.375]
 [0.625 0.375 0.   ]
 [0.    0.5   0.5  ]
 [0.    0.875 0.125]
 [1.    0.    0.   ]
 [0.    0.875 0.125]
 [0.    0.125 0.875]
 [0.    0.375 0.625]
 [1.    0.    0.   ]
 [0.125 0.875 0.   ]
 [0.    0.375 0.625]
 [0.    0.25  0.75 ]
 [1.    0.    0.   ]
 [0.    0.5   0.5  ]
 [1.    0.    0.   ]
 [0.    0.375 0.625]
 [0.    0.125 0.875]
 [0.    0.125 0.875]
 [0.    0.625 0.375]
 [0.    0.375 0.625]
 [0.    0.25  0.75 

### Decision Border Plot