In [1]:
import numpy as np
np.random.seed(42)
from sklearn import datasets

### Dataset preparation

In [2]:
iris = datasets.load_iris()

# x = iris.data[:, 1:3]
x = iris.data[:, :]
# x = iris.data[:, :3]
# x = iris.data[:, 1:4]
# x = iris.data[:, 2:4] # [2, 3]

y = iris.target

class_names = iris.target_names
discription = iris.DESCR

In [3]:
# print(f"class_names:\n{class_names}")
# print(f"discription:\n{discription}")

In [4]:
# print(f"x shape:\n{x.shape}")
# print(f"y shape:\n{y.shape}")

# print(f"x:\n{x}")
# print(f"y:\n{y}")

### Dataset Split

In [5]:
num_samples = x.shape[0]
num_features = x.shape[1]
num_classes = y.shape[0]

print(f"num_samples: {num_samples}")
print(f"num_features: {num_features}")
print(f"num_classes: {num_classes}")

num_samples: 150
num_features: 4
num_classes: 150


In [6]:
test_size = num_samples // 3
random_idxs = np.random.permutation(num_samples)

x_train = x[random_idxs[:-test_size]]
y_train = y[random_idxs[:-test_size]]

x_test = x[random_idxs[-test_size:]]
y_test = y[random_idxs[-test_size:]]

In [7]:
print(f"x_train shape:\n{x_train.shape}")
print(f"y_train shape:\n{y_train.shape}")

print(f"x_test shape:\n{x_test.shape}")
print(f"y_test shape:\n{y_test.shape}")

x_train shape:
(100, 4)
y_train shape:
(100,)
x_test shape:
(50, 4)
y_test shape:
(50,)


### KNN Model

In [8]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train, y_train)

accuracy = clf.score(x_test, y_test)
print(f"accuracy: {accuracy*100.0:.4}%")

y_pred = clf.predict(x_test)
print(f"y_pred:\n{y_pred}")

accuracy: 96.0%
y_pred:
[0 0 0 2 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2
 2 1 2 1 1 2 2 0 1 1 0 1 2]


### Try different hyperparameters

In [9]:
n_neighbors = [n_neighbor for n_neighbor in range(1, 11)] # [1, 2, ..., 10]
weight_modes = ['uniform', 'distance']

# 10 x 2 = 20 Models
for n_neighbor in n_neighbors:
    for weight_mode in weight_modes:
        clf = KNeighborsClassifier(
            n_neighbors=n_neighbor,
            weights=weight_mode
        )
        clf.fit(x_train, y_train)
        accuracy = clf.score(x_test, y_test)
        print(f"Neighbors: {n_neighbor}  Weight: {weight_mode}  Score: {accuracy:.4}")

Neighbors: 1  Weight: uniform  Score: 0.96
Neighbors: 1  Weight: distance  Score: 0.96
Neighbors: 2  Weight: uniform  Score: 0.96
Neighbors: 2  Weight: distance  Score: 0.96
Neighbors: 3  Weight: uniform  Score: 0.96
Neighbors: 3  Weight: distance  Score: 0.96
Neighbors: 4  Weight: uniform  Score: 0.96
Neighbors: 4  Weight: distance  Score: 0.96
Neighbors: 5  Weight: uniform  Score: 0.96
Neighbors: 5  Weight: distance  Score: 0.96
Neighbors: 6  Weight: uniform  Score: 0.96
Neighbors: 6  Weight: distance  Score: 0.96
Neighbors: 7  Weight: uniform  Score: 0.96
Neighbors: 7  Weight: distance  Score: 0.96
Neighbors: 8  Weight: uniform  Score: 0.98
Neighbors: 8  Weight: distance  Score: 0.96
Neighbors: 9  Weight: uniform  Score: 0.96
Neighbors: 9  Weight: distance  Score: 0.96
Neighbors: 10  Weight: uniform  Score: 0.96
Neighbors: 10  Weight: distance  Score: 0.96


### Best KNN Model

In [10]:
clf = KNeighborsClassifier(
    n_neighbors=8,
    weights="uniform"
)
clf.fit(x_train, y_train)

accuracy = clf.score(x_test, y_test)
print(f"accuracy: {accuracy*100.0:.4}%")

y_pred = clf.predict(x_test)
print(f"y_pred:\n{y_pred}")

y_pred_proba = clf.predict_proba(x_test)
print(f"y_pred_proba:\n{y_pred_proba}")

accuracy: 98.0%
y_pred:
[0 0 0 1 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2
 2 1 2 1 1 2 2 0 1 1 0 1 2]
y_pred_proba:
[[1.    0.    0.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.5   0.5  ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.625 0.375]
 [0.    0.875 0.125]
 [0.    0.375 0.625]
 [0.    0.875 0.125]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.125 0.875]
 [0.    1.    0.   ]
 [0.    0.125 0.875]
 [0.    1.    0.   ]
 [0.    1.    0.   ]
 [0.    0.875 0.125]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    1.    0.   ]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.    1.   ]
 [0.    0.125 0.875]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.875 0.125]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [0.    1.    0.   ]
 [0.    0.125 0.875]
 [0.    0.875 0.125

### Decision Border Plot

In [11]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

cmap_background = ListedColormap([
    '#FFAAAA',
    '#AAAAFF',
    '#AAFFAA'
])
cmap_points = [
    'red',
    'blue', 
    'green'
]

def make_meshgrid(x: np.ndarray, y: np.ndarray):
    x = np.arange(
        np.min(x) - 1, np.max(x) + 1, 0.01
    ) # [4.0, 4.01, 4.02, .... 8.0]
    y = np.arange(
        np.min(y) - 1, np.max(y) + 1, 0.01
    ) # [2.0, 2.01, 2.02, .... 4.5]
    xx, yy = np.meshgrid(x, y)
    return xx, yy

def plot_contours(
    ax: plt.Axes,
    clf: KNeighborsClassifier,
    xx: np.ndarray,
    yy: np.ndarray,
    **params
) -> None:
    z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    z = np.reshape(z, (xx.shape))
    ax.contourf(xx, yy, z, **params)

def plot_decision_border(
    clf: KNeighborsClassifier,
    x_train: np.ndarray,
    y_train: np.ndarray,
    x_test: np.ndarray,
    y_test: np.ndarray
) -> None:
    fig, ax = plt.subplots()
    X0 = x_train[:, 0]
    X1 = x_train[:, 1]
    xx, yy = make_meshgrid(X0, X1)
    plot_contours(
        ax, clf, xx, yy, cmap=cmap_background, alpha=0.5
    )
    for idx, point in enumerate(x_train):
        plt.scatter(
            point[0], point[1],
            color=cmap_points[y_train[idx]],
            s=20.0, marker="o"
        )
    for idx, point in enumerate(x_test):
        plt.scatter(
            point[0], point[1],
            color=cmap_points[y_test[idx]],
            s=30.0, marker="*"
        )
    plt.show()

In [12]:
plot_decision_border(clf, x_train, y_train, x_test, y_test)

ValueError: query data dimension must match training data dimension