In [1]:
# Load Iris Dataset
import numpy as np
from sklearn import datasets

# Load Dataset with first 2 Features
iris = datasets.load_iris()
x = iris.data
y = iris.target
print(x.shape)
print(y.shape)

# Dataset variables
num_samples = x.shape[0]
num_features = x.shape[1]
num_classes = 3
test_size = 20
train_size = num_samples - test_size

# Split Data in Train and Testset
indices = np.random.permutation(num_samples)
x_train = x[indices[:-20]]
y_train = y[indices[:-20]]

x_test = x[indices[-20:]]
y_test = y[indices[-20:]]

(150, 4)
(150,)


In [2]:
# Training Size
print(x_train.shape)
print(y_train.shape)

# Testing Size
print(x_test.shape)
print(y_test.shape)

(130, 4)
(130,)
(20, 4)
(20,)


In [3]:
# Model
from sklearn.neighbors import KNeighborsClassifier

neighbors = [i for i in range(1, 10)]
weights = ["uniform", "distance"]

for neighbor in neighbors:
    for weight in weights:
        knn = KNeighborsClassifier(n_neighbors=neighbor, weights=weight)
        knn.fit(x_train, y_train)
        score = knn.score(x_test, y_test)
        print("Score for setup: ", neighbor, " Neighbours, " , weight, " Weight Function - Score = ", score)

Score for setup:  1  Neighbours,  uniform  Weight Function - Score =  0.95
Score for setup:  1  Neighbours,  distance  Weight Function - Score =  0.95
Score for setup:  2  Neighbours,  uniform  Weight Function - Score =  0.95
Score for setup:  2  Neighbours,  distance  Weight Function - Score =  0.95
Score for setup:  3  Neighbours,  uniform  Weight Function - Score =  0.95
Score for setup:  3  Neighbours,  distance  Weight Function - Score =  0.95
Score for setup:  4  Neighbours,  uniform  Weight Function - Score =  0.9
Score for setup:  4  Neighbours,  distance  Weight Function - Score =  0.95
Score for setup:  5  Neighbours,  uniform  Weight Function - Score =  0.95
Score for setup:  5  Neighbours,  distance  Weight Function - Score =  0.95
Score for setup:  6  Neighbours,  uniform  Weight Function - Score =  0.95
Score for setup:  6  Neighbours,  distance  Weight Function - Score =  0.95
Score for setup:  7  Neighbours,  uniform  Weight Function - Score =  0.95
Score for setup:  7 

In [4]:
# Use "best Setup"
best_neighbor = 3
best_weight = "uniform"

knn = KNeighborsClassifier(n_neighbors=best_neighbor, weights=best_weight)
knn.fit(x_train, y_train)

pred = knn.predict(x_test)
pred_prob = knn.predict_proba(x_test)

print("Predictions vs. Classes:")
print("Pred:  ", pred)
print("Class: ", y_test)
print("\nPrediction Probs:")
print(pred_prob)

Predictions vs. Classes:
Pred:   [2 2 2 0 1 2 2 1 1 0 1 1 1 0 1 2 0 0 1 0]
Class:  [2 2 2 0 1 2 2 1 2 0 1 1 1 0 1 2 0 0 1 0]

Prediction Probs:
[[0.         0.         1.        ]
 [0.         0.33333333 0.66666667]
 [0.         0.         1.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         0.33333333 0.66666667]
 [0.         1.         0.        ]
 [0.         1.         0.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.66666667 0.33333333]
 [0.         1.         0.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [1.         0.         0.        ]]
