In [1]:
import numpy as np
from sklearn import datasets


np.random.seed(42)

### Dataset preparation

In [2]:
iris = datasets.load_iris()

x = iris.data
y = iris.target

class_names = iris.target_names
discription = iris.DESCR

In [3]:
print(f"class_names:\n{class_names}")
print(f"discription:\n{discription}")

class_names:
['setosa' 'versicolor' 'virginica']
discription:
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  

In [4]:
print(f"x shape:\n{x.shape}")
print(f"y shape:\n{y.shape}")

print(f"x:\n{x[:3]}")
print(f"y:\n{y[:3]}")

x shape:
(150, 4)
y shape:
(150,)
x:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y:
[0 0 0 0 0]
