In [2]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits
from sklearn.metrics import *
from sklearn.model_selection import *
from sklearn.preprocessing import *

#### LOAD DATASET

In [3]:
mnist = load_digits()
x, y = mnist.data, mnist.target
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.3)

#### NORMALIZE DATASET

In [4]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

#### KNN CLASSIFICATION

In [5]:
from sklearn.neighbors import KNeighborsClassifier

params = {"n_neighbors": [i for i in range(2, 22, 2)]}

clf = KNeighborsClassifier()
grid = GridSearchCV(clf, params, cv=3)

grid_result = grid.fit(x_train, y_train)

# Summary
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_["mean_test_score"]
stds = grid_result.cv_results_["std_test_score"]
params = grid_result.cv_results_["params"]

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.961814 using {'n_neighbors': 6}
0.954654 (0.008149) with: {'n_neighbors': 2}
0.957836 (0.004777) with: {'n_neighbors': 4}
0.961814 (0.001815) with: {'n_neighbors': 6}
0.958632 (0.004794) with: {'n_neighbors': 8}
0.954654 (0.005104) with: {'n_neighbors': 10}
0.949881 (0.001558) with: {'n_neighbors': 12}
0.949085 (0.009269) with: {'n_neighbors': 14}
0.946698 (0.009216) with: {'n_neighbors': 16}
0.940334 (0.008104) with: {'n_neighbors': 18}
0.939539 (0.009658) with: {'n_neighbors': 20}


In [7]:
regr = KNeighborsClassifier(n_neighbors=6)
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print("ACC: ", acc)

ACC:  0.9722222222222222


#### RANDOM FOREST CLASSIFICATION

In [12]:
from sklearn.ensemble import RandomForestClassifier

params = {"n_estimators": [340],
         "max_depth": [i for i in range(20, 52, 2)]}

clf = RandomForestClassifier()
grid = GridSearchCV(clf, params, cv=3, n_jobs=-1)

grid_result = grid.fit(x_train, y_train)

# Summary
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_["mean_test_score"]
stds = grid_result.cv_results_["std_test_score"]
params = grid_result.cv_results_["params"]

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.972156 using {'max_depth': 30, 'n_estimators': 340}
0.969769 (0.006612) with: {'max_depth': 20, 'n_estimators': 340}
0.968974 (0.001707) with: {'max_depth': 22, 'n_estimators': 340}
0.966587 (0.003145) with: {'max_depth': 24, 'n_estimators': 340}
0.965792 (0.002029) with: {'max_depth': 26, 'n_estimators': 340}
0.965792 (0.006043) with: {'max_depth': 28, 'n_estimators': 340}
0.972156 (0.006631) with: {'max_depth': 30, 'n_estimators': 340}
0.964996 (0.005680) with: {'max_depth': 32, 'n_estimators': 340}
0.964200 (0.003618) with: {'max_depth': 34, 'n_estimators': 340}
0.968974 (0.003176) with: {'max_depth': 36, 'n_estimators': 340}
0.968974 (0.003176) with: {'max_depth': 38, 'n_estimators': 340}
0.967383 (0.007881) with: {'max_depth': 40, 'n_estimators': 340}
0.967383 (0.004655) with: {'max_depth': 42, 'n_estimators': 340}
0.966587 (0.001829) with: {'max_depth': 44, 'n_estimators': 340}
0.967383 (0.002731) with: {'max_depth': 46, 'n_estimators': 340}
0.967383 (0.003807) with: {'ma

In [13]:
regr = RandomForestClassifier(max_depth=30, n_estimators=340)
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print("ACC: ", acc)

ACC:  0.9740740740740741


#### GRADIENT BOOSTING CLASSIFICATION

In [15]:
from sklearn.ensemble import GradientBoostingClassifier

params = {"n_estimators": [340],
         "max_depth": [i for i in range(20, 52, 2)],
         "learning_rate": [0.07]}

clf = GradientBoostingClassifier()
grid = GridSearchCV(clf, params, cv=3, n_jobs=-1)

grid_result = grid.fit(x_train, y_train)

# Summary
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_["mean_test_score"]
stds = grid_result.cv_results_["std_test_score"]
params = grid_result.cv_results_["params"]

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.893397 using {'learning_rate': 0.07, 'max_depth': 38, 'n_estimators': 340}
0.891806 (0.009045) with: {'learning_rate': 0.07, 'max_depth': 20, 'n_estimators': 340}
0.891806 (0.010196) with: {'learning_rate': 0.07, 'max_depth': 22, 'n_estimators': 340}
0.891010 (0.014176) with: {'learning_rate': 0.07, 'max_depth': 24, 'n_estimators': 340}
0.890215 (0.012423) with: {'learning_rate': 0.07, 'max_depth': 26, 'n_estimators': 340}
0.890215 (0.011002) with: {'learning_rate': 0.07, 'max_depth': 28, 'n_estimators': 340}
0.890215 (0.013157) with: {'learning_rate': 0.07, 'max_depth': 30, 'n_estimators': 340}
0.891010 (0.016120) with: {'learning_rate': 0.07, 'max_depth': 32, 'n_estimators': 340}
0.889419 (0.014110) with: {'learning_rate': 0.07, 'max_depth': 34, 'n_estimators': 340}
0.890215 (0.011439) with: {'learning_rate': 0.07, 'max_depth': 36, 'n_estimators': 340}
0.893397 (0.011162) with: {'learning_rate': 0.07, 'max_depth': 38, 'n_estimators': 340}
0.891806 (0.009306) with: {'learning_

In [17]:
regr = GradientBoostingClassifier(max_depth=50, n_estimators=240, learning_rate=0.07)
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print("ACC: ", acc)

ACC:  0.9333333333333333


#### SVM CLASSIFICATION:

In [18]:
from sklearn.svm import SVC

params = {"kernel": ["linear", "sigmoid", "rbf", "poly"]}

clf = SVC()
grid = GridSearchCV(clf, params, cv=3, n_jobs=-1)

grid_result = grid.fit(x_train, y_train)

# Summary
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_["mean_test_score"]
stds = grid_result.cv_results_["std_test_score"]
params = grid_result.cv_results_["params"]

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.972156 using {'kernel': 'rbf'}
0.968178 (0.008364) with: {'kernel': 'linear'}
0.945903 (0.004744) with: {'kernel': 'sigmoid'}
0.972156 (0.006230) with: {'kernel': 'rbf'}
0.893397 (0.018509) with: {'kernel': 'poly'}


In [19]:
regr = SVC(kernel="rbf")
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print("ACC: ", acc)

ACC:  0.9796296296296296


#### BEST MODEL:

In [20]:
regr = SVC(kernel="rbf")
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  2 51  0  1  0  0  0  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  0  0 66  0  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  1  0  0 53  0  1]
 [ 0  0  1  1  0  0  0  0 41  0]
 [ 0  0  0  0  0  1  1  0  2 55]]
