In [1]:
import numpy as np

In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x)
print(x.dtype)

x = x.astype(np.int8)
print(x)
print(x.dtype)

x = x.astype(np.float64)
print(x)
print(x.dtype)

x = x.astype(np.float32)
print(x)
print(x.dtype)

[1 2 3 4 5]
int32
[1 2 3 4 5]
int8
[1. 2. 3. 4. 5.]
float64
[1. 2. 3. 4. 5.]
float32


In [26]:
my_array = np.arange(10)
print(my_array)

my_array2 = np.linspace(start=0.0, stop=2.5, num=20)
print(my_array2)
print(my_array2.shape)

[0 1 2 3 4 5 6 7 8 9]
[0.         0.13157895 0.26315789 0.39473684 0.52631579 0.65789474
 0.78947368 0.92105263 1.05263158 1.18421053 1.31578947 1.44736842
 1.57894737 1.71052632 1.84210526 1.97368421 2.10526316 2.23684211
 2.36842105 2.5       ]
(20,)
