In [4]:
import numpy as np

my_array = np.array([1.0, 2.0, 3.0])
print(my_array)
print(len(my_array))
print(my_array.shape)

[1. 2. 3.]
3
(3,)


In [7]:
my_array = np.array([1, 2, 3, 4])
print(my_array.shape)

my_array = np.reshape(my_array, (1,4))
print(my_array.shape)

my_array = np.reshape(my_array, (4,1))
print(my_array.shape)

my_array = np.reshape(my_array, (2,2))
print(my_array.shape)
print(my_array)

(4,)
(1, 4)
(4, 1)
(2, 2)
[[1 2]
 [3 4]]


In [17]:
my_zero = np.zeros(shape=(3,3))
print(my_zero)

my_one = np.ones(shape=(3,3))
print(my_one)

my_array = np.full(shape=(3,3), fill_value=0.25)
print(my_array)

print(np.dot(my_one, my_array))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]]
[[0.75 0.75 0.75]
 [0.75 0.75 0.75]
 [0.75 0.75 0.75]]


In [16]:
my_array = np.array([-1, 0, 1])

print(np.argmax(my_array))
print(np.argmin(my_array))
print(np.max(my_array))
print(np.min(my_array))

2
0
1
-1
